/** Unified per-project pipeline HTTP API (eval → Phase1 → Phase2). */
import Database from "better-sqlite3";import {join} from "node:path";import {createSqlitePhase2Db} from "../db/phase2/sqlite-store.js";import {advanceProjectPipeline,type ProjectPipelineServices} from "../pipeline/project-pipeline.js";import {Phase1Service} from "../judge/phase1-service.js";import {GatewayPhase2Analyst} from "../judge/phase2/analyst.js";import {runPhase2Campaign} from "../judge/phase2/run-campaign.js";import {publishPhase2ArchiveView} from "../judge/results/publish-phase2-view.js";import {ModelGateway} from "../judge/gateway/client.js";import {startQueueContainer} from "../runner/queue-worker.js";import {badRequest,notFound} from "./errors.js";import {readJsonBody,sendJson,type Router} from "./router.js";import {createLiveQueueContainersMap} from "../runner/queue-worker.js";
type App={dataDir:string;queries:import("../db/queries.js").QueryStore};
function appOf(ctx:{app:unknown}):App{return ctx.app as App}
function openPhase2Db(dataDir:string){return createSqlitePhase2Db(new Database(join(dataDir,"themis.sqlite")))}
function archiveDirFor(app:App,runId:string):string{const row=app.queries.getEvalArchive(runId);const {archiveStoreDir}=require("../runner/archive-store.js") as typeof import("../runner/archive-store.js");const legacy=archiveStoreDir(app.dataDir,runId);return row?join(app.dataDir,"projects",row.projectId,"evals",runId):legacy}
function makeServices(app:App,phase1:Phase1Service):ProjectPipelineServices{const live=createLiveQueueContainersMap();return{async startEvalQueue(generation){const cfg=JSON.parse(generation.configJson||"{}") as {evalQueueId?:string};const queueId=cfg.evalQueueId;if(!queueId)throw new Error("generation config missing evalQueueId");if(live.get(queueId)||app.queries.getActiveQueueContainer(queueId))return{started:false};try{await startQueueContainer(app.dataDir,app.queries,queueId,live,{});return{started:true}}catch(e){if((e as {code?:string})?.code==="ALREADY_ACTIVE")return{started:false};throw e}},async pollEvalItem(item,generation){const cfg=JSON.parse(generation.configJson||"{}") as {evalQueueId?:string};const queueId=cfg.evalQueueId;if(!queueId)throw new Error("generation config missing evalQueueId");const queueItems=app.queries.listEvalQueueItems(queueId).filter(x=>x.enabled);const qi=queueItems.find(x=>x.taskId===item.evalId);if(!qi)return{state:"failed",error:`eval queue item not found for ${item.evalId}`};const projectId=app.queries.getEvalQueue(queueId)?.projectId;const runs=projectId?app.queries.listRuns({projectId}).filter(r=>r.queueItemId===qi.id):[];const run=runs.at(-1);if(!run)return{state:"running"};if(run.status==="failed"||run.error)return{state:"failed",runId:run.id,error:run.error??"eval run failed"};if(run.status==="completed"||run.status==="done"){const row=app.queries.getEvalArchive(run.id);return row?{state:"completed",runId:run.id,archiveId:row.runId}:{state:"running",runId:run.id}}return{state:"running",runId:run.id}},async startPhase1(item){if(!item.runId)throw new Error(`item ${item.id} missing runId`);const r=await phase1.start({runId:item.runId,archiveDir:archiveDirFor(app,item.runId)});return{operationId:r.operationId}},async getPhase1Status(runId){const s=await phase1.status(runId);if(s.state==="not_started")return{state:"running"};if(s.state==="failed")return{state:"failed",error:s.error};return{state:s.state,resultVersionId:s.resultVersionId,archiveViewId:s.archiveViewId}},async runPhase2(campaign,members){const gateway=ModelGateway.fromEnv();const analyst=new GatewayPhase2Analyst(gateway,`phase2_${campaign.id}`);const viewDirs=members.map(m=>join(app.dataDir,"judge_views",m.runId));const out=await runPhase2Campaign({campaignId:campaign.id,projectId:campaign.projectId,sutFingerprint:campaign.sutFingerprint,viewDirs,outputDir:join(app.dataDir,"phase2_artifacts",campaign.id),analyst});return{developerPackSha256:out.developerPackSha256,artifactDir:out.artifactDir}},async publishFinalView({campaign,member,phase2ArtifactDir}){const r=await publishPhase2ArchiveView({runId:member.runId,campaignId:campaign.id,phase1ViewDir:join(app.dataDir,"judge_views",member.runId),phase2ArtifactDir,viewDir:join(app.dataDir,"judge_final_views",member.runId)});return{finalArchiveViewId:r.manifestSha256,manifestSha256:r.manifestSha256}}}}
export function registerPipelineRoutes(router:Router,phase1:Phase1Service):void{
 router.post("/api/projects/:id/pipeline",async(req,res,ctx)=>{const app=appOf(ctx);const projectId=ctx.params.id!;app.queries.getProject(projectId);const body=await readJsonBody<{name?:string;eval_queue_id?:string;auto_phase2?:boolean}>(req);if(typeof body.eval_queue_id!=="string")throw badRequest("eval_queue_id is required");const db=openPhase2Db(app.dataDir);try{const q=await db.pipeline.createQueue({projectId,evalQueueId:body.eval_queue_id,name:body.name??"pipeline",autoPhase2:body.auto_phase2??true});sendJson(res,201,q)}finally{await db.close()}});
 router.post("/api/projects/:id/pipeline/generation",async(req,res,ctx)=>{const app=appOf(ctx);const projectId=ctx.params.id!;const db=openPhase2Db(app.dataDir);try{const q=await db.pipeline.getQueueByProject(projectId);if(!q)throw notFound("pipeline queue not found");const evalQueue=app.queries.getEvalQueue(q.evalQueueId);if(!evalQueue)throw notFound("linked eval queue not found");const items=app.queries.listEvalQueueItems(evalQueue.id).filter(x=>x.enabled);const g=await db.pipeline.createGeneration({queueId:q.id,configJson:JSON.stringify({evalQueueId:evalQueue.id,projectId})});for(let i=0;i<items.length;i++){const t=items[i];if(t)await db.pipeline.addItem({generationId:g.id,evalId:t.taskId,ordinal:i+1})}sendJson(res,201,g)}finally{await db.close()}});
 router.post("/api/projects/:id/pipeline/generation/:generationId/advance",async(req,res,ctx)=>{const app=appOf(ctx);const db=openPhase2Db(app.dataDir);try{const body=await readJsonBody<{trigger?:string}>(req);const r=await advanceProjectPipeline({db,services:makeServices(app,phase1),generationId:ctx.params.generationId!,trigger:(body.trigger as "auto"|"eval"|"phase1"|"phase2"|"finalize")??"auto"});sendJson(res,200,{generation:r.generation,items:r.items,waitingFor:r.waitingFor})}finally{await db.close()}});
 router.get("/api/projects/:id/pipeline/generation/:generationId",async(_req,res,ctx)=>{const app=appOf(ctx);const db=openPhase2Db(app.dataDir);try{const g=await db.pipeline.getGeneration(ctx.params.generationId!);if(!g)throw notFound("generation not found");const items=(await db.pipeline.listItems(g.id,{cursor:null,limit:1000})).items;const campaign=await db.phase2.getCampaignByGeneration(g.id);sendJson(res,200,{generation:g,items,campaign})}finally{await db.close()}});
 router.get("/api/projects/:id/pipeline/campaign/:campaignId",async(_req,res,ctx)=>{const app=appOf(ctx);const db=openPhase2Db(app.dataDir);try{const c=await db.phase2.getCampaign(ctx.params.campaignId!);if(!c)throw notFound("campaign not found");const records=(await db.phase2.listRecords(c.id,null,{cursor:null,limit:1000})).items;sendJson(res,200,{campaign:c,records})}finally{await db.close()}});
}
