/** Reusable real Phase-1 service for HTTP routes and unified pipeline wiring. */
import Database from "better-sqlite3";import {mkdir} from "node:fs/promises";import {join} from "node:path";import type {ModelGateway} from "./gateway/client.js";import {ModelGateway as Gateway} from "./gateway/client.js";import {runPhase1} from "./graph/graph.js";import {piConnectionFor} from "./pi/runtime.js";import type {StoredModelConfig} from "../config/model-config.js";import {publishJudgeArchiveView} from "./results/publish-view.js";import {migrate} from "../db/sqlite/migrate.js";import {advanceCurrentPointer} from "../db/sqlite/pointers.js";import {listResultVersionsByRun,upsertResultVersion} from "../db/sqlite/results.js";
export type Phase1ServiceStatus={state:"not_started"|"running"|"published"|"failed";resultVersionId?:string;archiveViewId?:string;error?:string};
/** Runs Phase1 asynchronously and persists the immutable result/view. */
export class Phase1Service{private running=new Map<string,Promise<void>>();private errors=new Map<string,string>();constructor(private dataDir:string,private gateway?:ModelGateway){}
 private gw(){if(!this.gateway)this.gateway=Gateway.fromEnv();return this.gateway}
 async start(input:{runId:string;archiveDir:string;trackId?:string;projectModelConfig?:StoredModelConfig|null}):Promise<{operationId:string}>{const operationId=`phase1:${input.runId}:${input.trackId??"default"}`;if(this.running.has(input.runId))return{operationId};const workDir=join(this.dataDir,"judge_work",`case_${input.runId}`),viewDir=join(this.dataDir,"judge_views",input.runId);await mkdir(workDir,{recursive:true});await mkdir(viewDir,{recursive:true});this.errors.delete(input.runId);const task=(async()=>{const state=await runPhase1({caseId:`case_${input.runId}`,runId:input.runId,archiveDir:input.archiveDir,workDir,gateway:this.gw(),attemptId:`att_${input.runId}_${Date.now()}`,pi:piConnectionFor("phase1",process.env,input.projectModelConfig)});const p=await publishJudgeArchiveView({runId:input.runId,trackId:input.trackId??"default",baseArchiveDir:input.archiveDir,judgeDir:join(workDir,"node4","judge"),viewDir,traceDir:join(workDir,"node4")});const db=new Database(join(this.dataDir,"themis.sqlite"));try{migrate(db);const stored=upsertResultVersion(db,p.result);advanceCurrentPointer(db,{runId:input.runId,trackId:stored.trackId,resultVersionId:stored.id,archiveViewPath:stored.archiveViewPath??viewDir,baseManifestSha256:stored.reportSha256,expectedResultVersionId:null})}finally{db.close()}})().catch(e=>{this.errors.set(input.runId,e instanceof Error?e.message:String(e))}).finally(()=>this.running.delete(input.runId));this.running.set(input.runId,task);return{operationId}}
 async status(runId:string):Promise<Phase1ServiceStatus>{if(this.running.has(runId))return{state:"running"};const err=this.errors.get(runId);if(err)return{state:"failed",error:err};const db=new Database(join(this.dataDir,"themis.sqlite"));try{migrate(db);const rows=listResultVersionsByRun(db,runId);const r=rows.at(-1);return r?{state:"published",resultVersionId:r.id,archiveViewId:r.archiveViewPath??join(this.dataDir,"judge_views",runId)}:{state:"not_started"}}finally{db.close()}}
 /** Pause the PI courtroom for this run. Session jsonl is kept for resume. */
 async pause(runId:string):Promise<{killed:boolean;pid:number|null;workDir:string}>{const {pausePiWorkDir}=await import("./pi/runtime.js");const workDir=join(this.dataDir,"judge_work",`case_${runId}`,"node4");const r=await pausePiWorkDir(workDir);if(!r.killed){const alt=await pausePiWorkDir(join(this.dataDir,"judge_work",runId));return{...alt,workDir:join(this.dataDir,"judge_work",runId)}}return{...r,workDir}}
 /** Resume the same PI session (start() already --continues existing sessions). */
 async resume(input:{runId:string;archiveDir:string;trackId?:string;projectModelConfig?:StoredModelConfig|null}):Promise<{operationId:string}>{return this.start(input)}
}
