import pg from "pg";
import { migrate, schemaVersion } from "../src/db/postgres/migrate.ts";
const url = process.env.AGENTEVAL_DATABASE_URL;
if (!url) throw new Error("AGENTEVAL_DATABASE_URL required");
const pool = new pg.Pool({ connectionString: url });
await migrate(pool);
console.log("schemaVersion:", await schemaVersion(pool));
const t = await pool.query("select tablename from pg_tables where schemaname = current_schema() order by 1");
console.log("tables:", t.rows.map((r: any) => r.tablename).join(", "));
await migrate(pool);
console.log("replay ok");
await pool.end();
