/** PostgreSQL implementation of unified-pipeline and Phase-2 repositories. */
import pg, {type Pool, type PoolClient} from "pg";
import type {
  AddPipelineItemInput, AddPhase2MemberInput, CreatePhase2CampaignInput, CreatePhase2RecordInput,
  CreatePipelineGenerationInput, CreatePipelineQueueInput, Phase2CampaignMemberRow, Phase2CampaignRow,
  Phase2CampaignState, Phase2Db, Phase2Page, Phase2PageRequest, Phase2PublicationRow,
  Phase2RecordKind, Phase2RecordRow, Phase2Repository, PipelineEventRow, PipelineGenerationRow,
  PipelineGenerationState, PipelineItemPatch, PipelineItemRow, PipelineItemState, PipelineQueuePatch,
  PipelineQueueRow, PipelineRepository,
} from "./contracts.js";
import {migrate} from "../postgres/migrate.js";

type Q=Pool|PoolClient; type Row=Record<string,unknown>; const MAX=1000;
function id(p:string){return `${p}_${crypto.randomUUID().replace(/-/g,"")}`} function now(){return new Date().toISOString()}
function lim(n:number){if(!Number.isInteger(n)||n<1)throw new RangeError("limit must be positive");return Math.min(n,MAX)}
function cur(v:readonly(string|number)[]){return Buffer.from(JSON.stringify(v)).toString("base64url")}
function dec(v:string|null):(string|number)[]|null{if(v===null)return null;const x=JSON.parse(Buffer.from(v,"base64url").toString());if(!Array.isArray(x))throw new Error("invalid cursor");return x}
function ts(v:unknown){return v instanceof Date?v.toISOString():String(v)}
const bool=(v:unknown)=>v===true||v===1;
function qrow(r:Row):PipelineQueueRow{return{id:String(r.id),projectId:String(r.project_id),evalQueueId:String(r.eval_queue_id),name:String(r.name),status:r.status as PipelineQueueRow["status"],revision:Number(r.revision),autoEval:bool(r.auto_eval),autoPhase1:bool(r.auto_phase1),autoPhase2:bool(r.auto_phase2),createdAt:ts(r.created_at),updatedAt:ts(r.updated_at)}}
function grow(r:Row):PipelineGenerationRow{return{id:String(r.id),queueId:String(r.queue_id),ordinal:Number(r.ordinal),name:(r.name as string|null)??null,state:r.state as PipelineGenerationState,fencingToken:Number(r.fencing_token),configJson:String(r.config_json),createdAt:ts(r.created_at),updatedAt:ts(r.updated_at),completedAt:r.completed_at==null?null:ts(r.completed_at)}}
function irow(r:Row):PipelineItemRow{return{id:String(r.id),generationId:String(r.generation_id),ordinal:Number(r.ordinal),evalId:String(r.eval_id),state:r.state as PipelineItemState,runId:r.run_id as string|null,baseArchiveId:r.base_archive_id as string|null,phase1ResultVersionId:r.phase1_result_version_id as string|null,phase1ArchiveViewId:r.phase1_archive_view_id as string|null,finalArchiveViewId:r.final_archive_view_id as string|null,errorKind:r.error_kind as string|null,errorDetail:r.error_detail as string|null,retryCount:Number(r.retry_count??0),createdAt:ts(r.created_at),updatedAt:ts(r.updated_at)}}
function erow(r:Row):PipelineEventRow{return{id:String(r.id),generationId:String(r.generation_id),itemId:r.item_id as string|null,operationId:String(r.operation_id),eventType:String(r.event_type),payloadJson:String(r.payload_json),createdAt:ts(r.created_at)}}
function crow(r:Row):Phase2CampaignRow{return{id:String(r.id),projectId:String(r.project_id),pipelineGenerationId:String(r.pipeline_generation_id),ordinal:Number(r.ordinal ?? 1),state:r.state as Phase2CampaignState,fencingToken:Number(r.fencing_token),sutFingerprint:String(r.sut_fingerprint),ontologyVersion:String(r.ontology_version),membershipSha256:String(r.membership_sha256),configJson:String(r.config_json),developerPackSha256:r.developer_pack_sha256 as string|null,createdAt:ts(r.created_at),updatedAt:ts(r.updated_at),publishedAt:r.published_at==null?null:ts(r.published_at)}}
function mrow(r:Row):Phase2CampaignMemberRow{return{campaignId:String(r.campaign_id),pipelineItemId:String(r.pipeline_item_id),runId:String(r.run_id),phase1ResultVersionId:String(r.phase1_result_version_id),phase1ArchiveViewId:String(r.phase1_archive_view_id),validForAgentLearning:bool(r.valid_for_agent_learning),ordinal:Number(r.ordinal)}}
function rrow(r:Row):Phase2RecordRow{return{id:String(r.id),campaignId:String(r.campaign_id),kind:r.kind as Phase2RecordKind,signature:r.signature as string|null,owner:r.owner as string|null,status:r.status as string|null,sourceOperationId:String(r.source_operation_id),payloadJson:String(r.payload_json),createdAt:ts(r.created_at)}}
function prow(r:Row):Phase2PublicationRow{return{id:String(r.id),campaignId:String(r.campaign_id),runId:String(r.run_id),phase1ArchiveViewId:String(r.phase1_archive_view_id),finalArchiveViewId:String(r.final_archive_view_id),manifestSha256:String(r.manifest_sha256),state:r.state as Phase2PublicationRow["state"],createdAt:ts(r.created_at),publishedAt:r.published_at==null?null:ts(r.published_at)}}

export class PostgresPipelineRepository implements PipelineRepository{
 constructor(private db:Q){}
 async createQueue(x:CreatePipelineQueueInput){const k=id("pq"),t=now();await this.db.query(`INSERT INTO project_pipeline_queues(id,project_id,eval_queue_id,name,status,revision,auto_eval,auto_phase1,auto_phase2,created_at,updated_at) VALUES($1,$2,$3,$4,'running',1,$5,$6,$7,$8,$9)`,[k,x.projectId,x.evalQueueId,x.name,x.autoEval!==false,x.autoPhase1!==false,x.autoPhase2!==false,t,t]);return(await this.getQueue(k))!}
 async getQueue(k:string){const r=(await this.db.query(`SELECT * FROM project_pipeline_queues WHERE id=$1`,[k])).rows[0] as Row|undefined;return r?qrow(r):null}
 async getQueueByProject(k:string){const r=(await this.db.query(`SELECT * FROM project_pipeline_queues WHERE project_id=$1`,[k])).rows[0] as Row|undefined;return r?qrow(r):null}
 async updateQueue(k:string,rev:number,p:PipelineQueuePatch){const sets=[`revision=revision+1`,`updated_at=now()`],a:unknown[]=[];const put=(c:string,v:unknown)=>{a.push(v);sets.push(`${c}=$${a.length}`)};if(p.status!==undefined)put("status",p.status);if(p.name!==undefined)put("name",p.name);if(p.autoEval!==undefined)put("auto_eval",p.autoEval);if(p.autoPhase1!==undefined)put("auto_phase1",p.autoPhase1);if(p.autoPhase2!==undefined)put("auto_phase2",p.autoPhase2);const b=a.length;a.push(k,rev);const z=await this.db.query(`UPDATE project_pipeline_queues SET ${sets.join(",")} WHERE id=$${b+1} AND revision=$${b+2}`,a);return z.rowCount?(await this.getQueue(k)):null}
 async createGeneration(x:CreatePipelineGenerationInput){const k=id("pgen"),t=now();const r=await this.db.query(`INSERT INTO project_pipeline_generations(id,queue_id,ordinal,name,state,fencing_token,config_json,created_at,updated_at) VALUES($1,$2,(SELECT COALESCE(MAX(ordinal),0)+1 FROM project_pipeline_generations WHERE queue_id=$2),$3,'draft',0,$4,$5,$6) RETURNING *`,[k,x.queueId,x.name??null,x.configJson,t,t]);return grow(r.rows[0])}
 async getGeneration(k:string){const r=(await this.db.query(`SELECT * FROM project_pipeline_generations WHERE id=$1`,[k])).rows[0] as Row|undefined;return r?grow(r):null}
 async getCurrentGeneration(k:string){const r=(await this.db.query(`SELECT * FROM project_pipeline_generations WHERE queue_id=$1 AND state NOT IN ('completed','failed','cancelled') ORDER BY ordinal DESC LIMIT 1`,[k])).rows[0] as Row|undefined;return r?grow(r):null}
 async listGenerations(q:string,req:Phase2PageRequest):Promise<Phase2Page<PipelineGenerationRow>>{const n=lim(req.limit),c=dec(req.cursor);const r=c?await this.db.query(`SELECT * FROM project_pipeline_generations WHERE queue_id=$1 AND (ordinal<$2 OR (ordinal=$2 AND id<$3)) ORDER BY ordinal DESC,id DESC LIMIT $4`,[q,Number(c[0]),String(c[1]),n+1]):await this.db.query(`SELECT * FROM project_pipeline_generations WHERE queue_id=$1 ORDER BY ordinal DESC,id DESC LIMIT $2`,[q,n+1]);const more=r.rows.length>n,items=r.rows.slice(0,n).map(grow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cur([last.ordinal,last.id]):null}}
 async renameGeneration(k:string,name:string|null){const z=await this.db.query(`UPDATE project_pipeline_generations SET name=$1,updated_at=now() WHERE id=$2`,[name,k]);return z.rowCount?(await this.getGeneration(k)):null}
 async transitionGeneration(k:string,s:PipelineGenerationState,token:number,n:PipelineGenerationState){const z=await this.db.query(`UPDATE project_pipeline_generations SET state=$1,fencing_token=fencing_token+1,updated_at=now(),completed_at=CASE WHEN $1='completed' THEN now() ELSE completed_at END WHERE id=$2 AND state=$3 AND fencing_token=$4`,[n,k,s,token]);return z.rowCount?(await this.getGeneration(k)):null}
 async addItem(x:AddPipelineItemInput){const k=id("pitem"),t=now();const r=await this.db.query(`INSERT INTO project_pipeline_items(id,generation_id,ordinal,eval_id,state,created_at,updated_at) VALUES($1,$2,$3,$4,'eval_pending',$5,$6) RETURNING *`,[k,x.generationId,x.ordinal,x.evalId,t,t]);return irow(r.rows[0])}
 async getItem(k:string){const r=(await this.db.query(`SELECT * FROM project_pipeline_items WHERE id=$1`,[k])).rows[0] as Row|undefined;return r?irow(r):null}
 async listItems(g:string,req:Phase2PageRequest):Promise<Phase2Page<PipelineItemRow>>{const n=lim(req.limit),c=dec(req.cursor);const r=c?await this.db.query(`SELECT * FROM project_pipeline_items WHERE generation_id=$1 AND (ordinal>$2 OR (ordinal=$2 AND id>$3)) ORDER BY ordinal,id LIMIT $4`,[g,Number(c[0]),String(c[1]),n+1]):await this.db.query(`SELECT * FROM project_pipeline_items WHERE generation_id=$1 ORDER BY ordinal,id LIMIT $2`,[g,n+1]);const more=r.rows.length>n,items=r.rows.slice(0,n).map(irow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cur([last.ordinal,last.id]):null}}
 async updateItem(k:string,s:PipelineItemState,p:PipelineItemPatch){const sets=[`updated_at=now()`],a:unknown[]=[];const put=(c:string,v:unknown)=>{a.push(v);sets.push(`${c}=$${a.length}`)};for(const [key,col] of [["state","state"],["runId","run_id"],["baseArchiveId","base_archive_id"],["phase1ResultVersionId","phase1_result_version_id"],["phase1ArchiveViewId","phase1_archive_view_id"],["finalArchiveViewId","final_archive_view_id"],["errorKind","error_kind"],["errorDetail","error_detail"],["retryCount","retry_count"]] as const){if(p[key]!==undefined)put(col,p[key])}const b=a.length;a.push(k,s);const z=await this.db.query(`UPDATE project_pipeline_items SET ${sets.join(",")} WHERE id=$${b+1} AND state=$${b+2}`,a);return z.rowCount?(await this.getItem(k)):null}
 async appendEvent(x:Omit<PipelineEventRow,"id"|"createdAt">){const k=id("pevt"),t=now();const z=await this.db.query(`INSERT INTO project_pipeline_events(id,generation_id,item_id,operation_id,event_type,payload_json,created_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(operation_id) DO NOTHING`,[k,x.generationId,x.itemId,x.operationId,x.eventType,x.payloadJson,t]);const r=(await this.db.query(`SELECT * FROM project_pipeline_events WHERE operation_id=$1`,[x.operationId])).rows[0];return{event:erow(r),created:(z.rowCount??0)===1}}
 async listEvents(g:string,req:Phase2PageRequest):Promise<Phase2Page<PipelineEventRow>>{const n=lim(req.limit),c=dec(req.cursor);const r=c?await this.db.query(`SELECT * FROM project_pipeline_events WHERE generation_id=$1 AND (created_at>$2 OR (created_at=$2 AND id>$3)) ORDER BY created_at,id LIMIT $4`,[g,String(c[0]),String(c[1]),n+1]):await this.db.query(`SELECT * FROM project_pipeline_events WHERE generation_id=$1 ORDER BY created_at,id LIMIT $2`,[g,n+1]);const more=r.rows.length>n,items=r.rows.slice(0,n).map(erow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cur([last.createdAt,last.id]):null}}
}

export class PostgresPhase2Repository implements Phase2Repository{
 constructor(private db:Q){}
 async createCampaign(x:CreatePhase2CampaignInput){const k=id("p2c"),t=now();const r=await this.db.query(`INSERT INTO phase2_campaigns(id,project_id,pipeline_generation_id,ordinal,state,fencing_token,sut_fingerprint,ontology_version,membership_sha256,config_json,created_at,updated_at) SELECT $1,$2,$3,COALESCE(MAX(ordinal),0)+1,'draft',0,$4,$5,$6,$7,$8,$9 FROM phase2_campaigns WHERE pipeline_generation_id=$3 RETURNING *`,[k,x.projectId,x.pipelineGenerationId,x.sutFingerprint,x.ontologyVersion,x.membershipSha256,x.configJson,t,t]);return crow(r.rows[0])}
 async getCampaign(k:string){const r=(await this.db.query(`SELECT * FROM phase2_campaigns WHERE id=$1`,[k])).rows[0] as Row|undefined;return r?crow(r):null}
 async getCampaignByGeneration(k:string){const r=(await this.db.query(`SELECT * FROM phase2_campaigns WHERE pipeline_generation_id=$1 ORDER BY ordinal DESC LIMIT 1`,[k])).rows[0] as Row|undefined;return r?crow(r):null}
 async listCampaignsByGeneration(k:string):Promise<readonly Phase2CampaignRow[]>{return ((await this.db.query(`SELECT * FROM phase2_campaigns WHERE pipeline_generation_id=$1 ORDER BY ordinal`,[k])).rows as Row[]).map(crow)}
 async transitionCampaign(k:string,s:Phase2CampaignState,token:number,n:Phase2CampaignState){const z=await this.db.query(`UPDATE phase2_campaigns SET state=$1,fencing_token=fencing_token+1,updated_at=now(),published_at=CASE WHEN $1='published' THEN now() ELSE published_at END WHERE id=$2 AND state=$3 AND fencing_token=$4`,[n,k,s,token]);return z.rowCount?(await this.getCampaign(k)):null}
 async setCampaignDeveloperPackSha256(k:string,sha:string){const z=await this.db.query(`UPDATE phase2_campaigns SET developer_pack_sha256=$1,updated_at=now() WHERE id=$2`,[sha,k]);return z.rowCount?(await this.getCampaign(k)):null}
 async addMember(x:AddPhase2MemberInput){const r=await this.db.query(`INSERT INTO phase2_campaign_members(campaign_id,pipeline_item_id,run_id,phase1_result_version_id,phase1_archive_view_id,valid_for_agent_learning,ordinal) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[x.campaignId,x.pipelineItemId,x.runId,x.phase1ResultVersionId,x.phase1ArchiveViewId,x.validForAgentLearning,x.ordinal]);return mrow(r.rows[0])}
 async listMembers(k:string,req:Phase2PageRequest):Promise<Phase2Page<Phase2CampaignMemberRow>>{const n=lim(req.limit),c=dec(req.cursor);const r=c?await this.db.query(`SELECT * FROM phase2_campaign_members WHERE campaign_id=$1 AND (ordinal>$2 OR (ordinal=$2 AND run_id>$3)) ORDER BY ordinal,run_id LIMIT $4`,[k,Number(c[0]),String(c[1]),n+1]):await this.db.query(`SELECT * FROM phase2_campaign_members WHERE campaign_id=$1 ORDER BY ordinal,run_id LIMIT $2`,[k,n+1]);const more=r.rows.length>n,items=r.rows.slice(0,n).map(mrow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cur([last.ordinal,last.runId]):null}}
 async upsertRecord(x:CreatePhase2RecordInput){const k=id("p2r"),t=now();const z=await this.db.query(`INSERT INTO phase2_records(id,campaign_id,kind,signature,owner,status,source_operation_id,payload_json,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(campaign_id,kind,source_operation_id) DO NOTHING`,[k,x.campaignId,x.kind,x.signature??null,x.owner??null,x.status??null,x.sourceOperationId,x.payloadJson,t]);const r=(await this.db.query(`SELECT * FROM phase2_records WHERE campaign_id=$1 AND kind=$2 AND source_operation_id=$3`,[x.campaignId,x.kind,x.sourceOperationId])).rows[0];return{record:rrow(r),created:(z.rowCount??0)===1}}
 async listRecords(k:string,kind:Phase2RecordKind|null,req:Phase2PageRequest):Promise<Phase2Page<Phase2RecordRow>>{const n=lim(req.limit),c=dec(req.cursor),base=kind?[k,kind]:[k],where=kind?`campaign_id=$1 AND kind=$2`:`campaign_id=$1`;let r;if(c){const off=base.length;r=await this.db.query(`SELECT * FROM phase2_records WHERE ${where} AND (created_at>$${off+1} OR (created_at=$${off+1} AND id>$${off+2})) ORDER BY created_at,id LIMIT $${off+3}`,[...base,String(c[0]),String(c[1]),n+1])}else{r=await this.db.query(`SELECT * FROM phase2_records WHERE ${where} ORDER BY created_at,id LIMIT $${base.length+1}`,[...base,n+1])}const more=r.rows.length>n,items=r.rows.slice(0,n).map(rrow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cur([last.createdAt,last.id]):null}}
 async createPublication(x:Omit<Phase2PublicationRow,"id"|"state"|"createdAt"|"publishedAt">){const k=id("p2p"),t=now();const r=await this.db.query(`INSERT INTO phase2_artifact_publications(id,campaign_id,run_id,phase1_archive_view_id,final_archive_view_id,manifest_sha256,state,created_at) VALUES($1,$2,$3,$4,$5,$6,'preparing',$7) RETURNING *`,[k,x.campaignId,x.runId,x.phase1ArchiveViewId,x.finalArchiveViewId,x.manifestSha256,t]);return prow(r.rows[0])}
 async transitionPublication(k:string,s:Phase2PublicationRow["state"],n:Phase2PublicationRow["state"]){const z=await this.db.query(`UPDATE phase2_artifact_publications SET state=$1,published_at=CASE WHEN $1='published' THEN now() ELSE published_at END WHERE id=$2 AND state=$3`,[n,k,s]);if(!z.rowCount)return null;return prow((await this.db.query(`SELECT * FROM phase2_artifact_publications WHERE id=$1`,[k])).rows[0])}
 async listPublications(k:string,req:Phase2PageRequest):Promise<Phase2Page<Phase2PublicationRow>>{const n=lim(req.limit),c=dec(req.cursor);const r=c?await this.db.query(`SELECT * FROM phase2_artifact_publications WHERE campaign_id=$1 AND (created_at>$2 OR (created_at=$2 AND id>$3)) ORDER BY created_at,id LIMIT $4`,[k,String(c[0]),String(c[1]),n+1]):await this.db.query(`SELECT * FROM phase2_artifact_publications WHERE campaign_id=$1 ORDER BY created_at,id LIMIT $2`,[k,n+1]);const more=r.rows.length>n,items=r.rows.slice(0,n).map(prow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cur([last.createdAt,last.id]):null}}
}

/** Open PostgreSQL Phase-2 repositories on a dedicated pool. */
export async function createPostgresPhase2Db(databaseUrl:string):Promise<Phase2Db>{const pool=new pg.Pool({connectionString:databaseUrl,application_name:"agenteval-phase2"});await migrate(pool);const pipeline=new PostgresPipelineRepository(pool),phase2=new PostgresPhase2Repository(pool);return{pipeline,phase2,async transaction<T>(fn:(tx:Pick<Phase2Db,"pipeline"|"phase2">)=>Promise<T>){const c=await pool.connect();try{await c.query("BEGIN");const out=await fn({pipeline:new PostgresPipelineRepository(c),phase2:new PostgresPhase2Repository(c)});await c.query("COMMIT");return out}catch(e){await c.query("ROLLBACK").catch(()=>{});throw e}finally{c.release()}},async close(){await pool.end()}}}
