/** SQLite implementation of unified-pipeline and Phase-2 repositories. */
import type Database from "better-sqlite3";
import type {
  AddPipelineItemInput, AddPhase2MemberInput, CreatePhase2CampaignInput,
  CreatePhase2RecordInput, CreatePipelineGenerationInput, CreatePipelineQueueInput,
  Phase2CampaignMemberRow, Phase2CampaignRow, Phase2CampaignState, Phase2Db,
  Phase2Page, Phase2PageRequest, Phase2PublicationRow, Phase2RecordKind, Phase2RecordRow,
  Phase2Repository, PipelineEventRow, PipelineGenerationRow, PipelineGenerationState,
  PipelineItemPatch, PipelineItemRow, PipelineItemState, PipelineQueuePatch,
  PipelineQueueRow, PipelineRepository,
} from "./contracts.js";
import { migrate } from "../sqlite/migrate.js";

type Row = Record<string, unknown>;
const MAX_PAGE = 1000;
function id(prefix: string): string { return `${prefix}_${crypto.randomUUID().replace(/-/g, "")}`; }
function now(): string { return new Date().toISOString(); }
function limit(n: number): number { if (!Number.isInteger(n) || n < 1) throw new RangeError("limit must be positive"); return Math.min(n, MAX_PAGE); }
function cursor(values: readonly (string|number)[]): string { return Buffer.from(JSON.stringify(values)).toString("base64url"); }
function decode(c: string | null): (string|number)[] | null { if (c === null) return null; const v=JSON.parse(Buffer.from(c,"base64url").toString("utf8")); if(!Array.isArray(v)) throw new Error("invalid cursor"); return v as (string|number)[]; }
function b(v: unknown): boolean { return v === true || v === 1; }

function qrow(r: Row): PipelineQueueRow { return {id:String(r.id),projectId:String(r.project_id),evalQueueId:String(r.eval_queue_id),name:String(r.name),status:r.status as PipelineQueueRow["status"],revision:Number(r.revision),autoEval:b(r.auto_eval),autoPhase1:b(r.auto_phase1),autoPhase2:b(r.auto_phase2),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}; }
function grow(r: Row): PipelineGenerationRow { return {id:String(r.id),queueId:String(r.queue_id),ordinal:Number(r.ordinal),name:(r.name as string|null)??null,state:r.state as PipelineGenerationState,fencingToken:Number(r.fencing_token),configJson:String(r.config_json),createdAt:String(r.created_at),updatedAt:String(r.updated_at),completedAt:(r.completed_at as string|null)??null}; }
function irow(r: Row): PipelineItemRow { return {id:String(r.id),generationId:String(r.generation_id),ordinal:Number(r.ordinal),evalId:String(r.eval_id),state:r.state as PipelineItemState,runId:(r.run_id as string|null)??null,baseArchiveId:(r.base_archive_id as string|null)??null,phase1ResultVersionId:(r.phase1_result_version_id as string|null)??null,phase1ArchiveViewId:(r.phase1_archive_view_id as string|null)??null,finalArchiveViewId:(r.final_archive_view_id as string|null)??null,errorKind:(r.error_kind as string|null)??null,errorDetail:(r.error_detail as string|null)??null,retryCount:Number(r.retry_count??0),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}; }
function erow(r: Row): PipelineEventRow { return {id:String(r.id),generationId:String(r.generation_id),itemId:(r.item_id as string|null)??null,operationId:String(r.operation_id),eventType:String(r.event_type),payloadJson:String(r.payload_json),createdAt:String(r.created_at)}; }
function crow(r: Row): Phase2CampaignRow { return {id:String(r.id),projectId:String(r.project_id),pipelineGenerationId:String(r.pipeline_generation_id),ordinal:Number(r.ordinal ?? 1),state:r.state as Phase2CampaignState,fencingToken:Number(r.fencing_token),sutFingerprint:String(r.sut_fingerprint),ontologyVersion:String(r.ontology_version),membershipSha256:String(r.membership_sha256),configJson:String(r.config_json),developerPackSha256:(r.developer_pack_sha256 as string|null)??null,createdAt:String(r.created_at),updatedAt:String(r.updated_at),publishedAt:(r.published_at as string|null)??null}; }
function mrow(r: Row): Phase2CampaignMemberRow { return {campaignId:String(r.campaign_id),pipelineItemId:String(r.pipeline_item_id),runId:String(r.run_id),phase1ResultVersionId:String(r.phase1_result_version_id),phase1ArchiveViewId:String(r.phase1_archive_view_id),validForAgentLearning:b(r.valid_for_agent_learning),ordinal:Number(r.ordinal)}; }
function rrow(r: Row): Phase2RecordRow { return {id:String(r.id),campaignId:String(r.campaign_id),kind:r.kind as Phase2RecordKind,signature:(r.signature as string|null)??null,owner:(r.owner as string|null)??null,status:(r.status as string|null)??null,sourceOperationId:String(r.source_operation_id),payloadJson:String(r.payload_json),createdAt:String(r.created_at)}; }
function prow(r: Row): Phase2PublicationRow { return {id:String(r.id),campaignId:String(r.campaign_id),runId:String(r.run_id),phase1ArchiveViewId:String(r.phase1_archive_view_id),finalArchiveViewId:String(r.final_archive_view_id),manifestSha256:String(r.manifest_sha256),state:r.state as Phase2PublicationRow["state"],createdAt:String(r.created_at),publishedAt:(r.published_at as string|null)??null}; }

export class SqlitePipelineRepository implements PipelineRepository {
  constructor(private db: Database.Database) {}
  async createQueue(x: CreatePipelineQueueInput): Promise<PipelineQueueRow> { const t=now(),k=id("pq"); this.db.prepare(`INSERT INTO project_pipeline_queues(id,project_id,eval_queue_id,name,status,revision,auto_eval,auto_phase1,auto_phase2,created_at,updated_at) VALUES(?,?,?,?,'running',1,?,?,?,?,?)`).run(k,x.projectId,x.evalQueueId,x.name,x.autoEval===false?0:1,x.autoPhase1===false?0:1,x.autoPhase2===false?0:1,t,t); return (await this.getQueue(k))!; }
  async getQueue(k:string):Promise<PipelineQueueRow|null>{const r=this.db.prepare(`SELECT * FROM project_pipeline_queues WHERE id=?`).get(k) as Row|undefined;return r?qrow(r):null;}
  async getQueueByProject(k:string):Promise<PipelineQueueRow|null>{const r=this.db.prepare(`SELECT * FROM project_pipeline_queues WHERE project_id=?`).get(k) as Row|undefined;return r?qrow(r):null;}
  async updateQueue(k:string,rev:number,p:PipelineQueuePatch):Promise<PipelineQueueRow|null>{const sets:string[]=["revision=revision+1","updated_at=?"],a:unknown[]=[now()]; const put=(c:string,v:unknown)=>{sets.push(`${c}=?`);a.push(v)}; if(p.status!==undefined)put("status",p.status);if(p.name!==undefined)put("name",p.name);if(p.autoEval!==undefined)put("auto_eval",p.autoEval?1:0);if(p.autoPhase1!==undefined)put("auto_phase1",p.autoPhase1?1:0);if(p.autoPhase2!==undefined)put("auto_phase2",p.autoPhase2?1:0);a.push(k,rev);const z=this.db.prepare(`UPDATE project_pipeline_queues SET ${sets.join(",")} WHERE id=? AND revision=?`).run(...a);return z.changes?(await this.getQueue(k)):null;}
  async createGeneration(x:CreatePipelineGenerationInput):Promise<PipelineGenerationRow>{const k=id("pgen"),t=now();const ord=Number((this.db.prepare(`SELECT COALESCE(MAX(ordinal),0)+1 n FROM project_pipeline_generations WHERE queue_id=?`).get(x.queueId) as Row).n);this.db.prepare(`INSERT INTO project_pipeline_generations(id,queue_id,ordinal,name,state,fencing_token,config_json,created_at,updated_at) VALUES(?,?,?,?,'draft',0,?,?,?)`).run(k,x.queueId,ord,x.name??null,x.configJson,t,t);return (await this.getGeneration(k))!;}
  async getGeneration(k:string):Promise<PipelineGenerationRow|null>{const r=this.db.prepare(`SELECT * FROM project_pipeline_generations WHERE id=?`).get(k) as Row|undefined;return r?grow(r):null;}
  async getCurrentGeneration(k:string):Promise<PipelineGenerationRow|null>{const r=this.db.prepare(`SELECT * FROM project_pipeline_generations WHERE queue_id=? AND state NOT IN ('completed','failed','cancelled') ORDER BY ordinal DESC LIMIT 1`).get(k) as Row|undefined;return r?grow(r):null;}
  async listGenerations(q:string,req:Phase2PageRequest):Promise<Phase2Page<PipelineGenerationRow>>{const n=limit(req.limit),c=decode(req.cursor);const rows=(c?this.db.prepare(`SELECT * FROM project_pipeline_generations WHERE queue_id=? AND (ordinal<? OR (ordinal=? AND id<?)) ORDER BY ordinal DESC,id DESC LIMIT ?`).all(q,Number(c[0]),Number(c[0]),String(c[1]),n+1):this.db.prepare(`SELECT * FROM project_pipeline_generations WHERE queue_id=? ORDER BY ordinal DESC,id DESC LIMIT ?`).all(q,n+1)) as Row[];const more=rows.length>n,items=rows.slice(0,n).map(grow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cursor([last.ordinal,last.id]):null};}
  async renameGeneration(k:string,name:string|null):Promise<PipelineGenerationRow|null>{const z=this.db.prepare(`UPDATE project_pipeline_generations SET name=?,updated_at=? WHERE id=?`).run(name,now(),k);return z.changes?(await this.getGeneration(k)):null;}
  async transitionGeneration(k:string,s:PipelineGenerationState,token:number,n:PipelineGenerationState):Promise<PipelineGenerationRow|null>{const done=n==="completed"?now():null;const z=this.db.prepare(`UPDATE project_pipeline_generations SET state=?,fencing_token=fencing_token+1,updated_at=?,completed_at=COALESCE(?,completed_at) WHERE id=? AND state=? AND fencing_token=?`).run(n,now(),done,k,s,token);return z.changes?(await this.getGeneration(k)):null;}
  async addItem(x:AddPipelineItemInput):Promise<PipelineItemRow>{const k=id("pitem"),t=now();this.db.prepare(`INSERT INTO project_pipeline_items(id,generation_id,ordinal,eval_id,state,created_at,updated_at) VALUES(?,?,?,?,'eval_pending',?,?)`).run(k,x.generationId,x.ordinal,x.evalId,t,t);return (await this.getItem(k))!;}
  async getItem(k:string):Promise<PipelineItemRow|null>{const r=this.db.prepare(`SELECT * FROM project_pipeline_items WHERE id=?`).get(k) as Row|undefined;return r?irow(r):null;}
  async listItems(g:string,req:Phase2PageRequest):Promise<Phase2Page<PipelineItemRow>>{const n=limit(req.limit),c=decode(req.cursor);const rows=(c?this.db.prepare(`SELECT * FROM project_pipeline_items WHERE generation_id=? AND (ordinal>? OR (ordinal=? AND id>?)) ORDER BY ordinal,id LIMIT ?`).all(g,Number(c[0]),Number(c[0]),String(c[1]),n+1):this.db.prepare(`SELECT * FROM project_pipeline_items WHERE generation_id=? ORDER BY ordinal,id LIMIT ?`).all(g,n+1)) as Row[];const more=rows.length>n,items=rows.slice(0,n).map(irow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cursor([last.ordinal,last.id]):null};}
  async updateItem(k:string,s:PipelineItemState,p:PipelineItemPatch):Promise<PipelineItemRow|null>{const sets=["updated_at=?"],a:unknown[]=[now()];const put=(c:string,v:unknown)=>{sets.push(`${c}=?`);a.push(v)};for(const [key,col] of [["state","state"],["runId","run_id"],["baseArchiveId","base_archive_id"],["phase1ResultVersionId","phase1_result_version_id"],["phase1ArchiveViewId","phase1_archive_view_id"],["finalArchiveViewId","final_archive_view_id"],["errorKind","error_kind"],["errorDetail","error_detail"],["retryCount","retry_count"]] as const){if(p[key]!==undefined)put(col,p[key])}a.push(k,s);const z=this.db.prepare(`UPDATE project_pipeline_items SET ${sets.join(",")} WHERE id=? AND state=?`).run(...a);return z.changes?(await this.getItem(k)):null;}
  async appendEvent(x:Omit<PipelineEventRow,"id"|"createdAt">):Promise<{event:PipelineEventRow;created:boolean}>{const k=id("pevt"),t=now();const z=this.db.prepare(`INSERT OR IGNORE INTO project_pipeline_events(id,generation_id,item_id,operation_id,event_type,payload_json,created_at) VALUES(?,?,?,?,?,?,?)`).run(k,x.generationId,x.itemId,x.operationId,x.eventType,x.payloadJson,t);const r=this.db.prepare(`SELECT * FROM project_pipeline_events WHERE operation_id=?`).get(x.operationId) as Row;return{event:erow(r),created:z.changes===1};}
  async listEvents(g:string,req:Phase2PageRequest):Promise<Phase2Page<PipelineEventRow>>{const n=limit(req.limit),c=decode(req.cursor);const rows=(c?this.db.prepare(`SELECT * FROM project_pipeline_events WHERE generation_id=? AND (created_at>? OR (created_at=? AND id>?)) ORDER BY created_at,id LIMIT ?`).all(g,String(c[0]),String(c[0]),String(c[1]),n+1):this.db.prepare(`SELECT * FROM project_pipeline_events WHERE generation_id=? ORDER BY created_at,id LIMIT ?`).all(g,n+1)) as Row[];const more=rows.length>n,items=rows.slice(0,n).map(erow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cursor([last.createdAt,last.id]):null};}
}

export class SqlitePhase2Repository implements Phase2Repository {
  constructor(private db: Database.Database) {}
  async createCampaign(x:CreatePhase2CampaignInput):Promise<Phase2CampaignRow>{const k=id("p2c"),t=now();const nx=(this.db.prepare(`SELECT COALESCE(MAX(ordinal),0)+1 AS n FROM phase2_campaigns WHERE pipeline_generation_id=?`).get(x.pipelineGenerationId) as {n:number}).n;this.db.prepare(`INSERT INTO phase2_campaigns(id,project_id,pipeline_generation_id,ordinal,state,fencing_token,sut_fingerprint,ontology_version,membership_sha256,config_json,created_at,updated_at) VALUES(?,?,?,?,'draft',0,?,?,?,?,?,?)`).run(k,x.projectId,x.pipelineGenerationId,nx,x.sutFingerprint,x.ontologyVersion,x.membershipSha256,x.configJson,t,t);return (await this.getCampaign(k))!;}
  async getCampaign(k:string):Promise<Phase2CampaignRow|null>{const r=this.db.prepare(`SELECT * FROM phase2_campaigns WHERE id=?`).get(k) as Row|undefined;return r?crow(r):null;}
  async getCampaignByGeneration(k:string):Promise<Phase2CampaignRow|null>{const r=this.db.prepare(`SELECT * FROM phase2_campaigns WHERE pipeline_generation_id=? ORDER BY ordinal DESC LIMIT 1`).get(k) as Row|undefined;return r?crow(r):null;}
  async listCampaignsByGeneration(k:string):Promise<readonly Phase2CampaignRow[]>{return (this.db.prepare(`SELECT * FROM phase2_campaigns WHERE pipeline_generation_id=? ORDER BY ordinal`).all(k) as Row[]).map(crow);}
  async transitionCampaign(k:string,s:Phase2CampaignState,token:number,n:Phase2CampaignState):Promise<Phase2CampaignRow|null>{const pub=n==="published"?now():null;const z=this.db.prepare(`UPDATE phase2_campaigns SET state=?,fencing_token=fencing_token+1,updated_at=?,published_at=COALESCE(?,published_at) WHERE id=? AND state=? AND fencing_token=?`).run(n,now(),pub,k,s,token);return z.changes?(await this.getCampaign(k)):null;}
  async setCampaignDeveloperPackSha256(k:string,sha:string):Promise<Phase2CampaignRow|null>{const z=this.db.prepare(`UPDATE phase2_campaigns SET developer_pack_sha256=?,updated_at=? WHERE id=?`).run(sha,now(),k);return z.changes?(await this.getCampaign(k)):null;}
  async addMember(x:AddPhase2MemberInput):Promise<Phase2CampaignMemberRow>{this.db.prepare(`INSERT INTO phase2_campaign_members(campaign_id,pipeline_item_id,run_id,phase1_result_version_id,phase1_archive_view_id,valid_for_agent_learning,ordinal) VALUES(?,?,?,?,?,?,?)`).run(x.campaignId,x.pipelineItemId,x.runId,x.phase1ResultVersionId,x.phase1ArchiveViewId,x.validForAgentLearning?1:0,x.ordinal);return mrow(this.db.prepare(`SELECT * FROM phase2_campaign_members WHERE campaign_id=? AND pipeline_item_id=?`).get(x.campaignId,x.pipelineItemId) as Row);}
  async listMembers(k:string,req:Phase2PageRequest):Promise<Phase2Page<Phase2CampaignMemberRow>>{const n=limit(req.limit),c=decode(req.cursor);const rows=(c?this.db.prepare(`SELECT * FROM phase2_campaign_members WHERE campaign_id=? AND (ordinal>? OR (ordinal=? AND run_id>?)) ORDER BY ordinal,run_id LIMIT ?`).all(k,Number(c[0]),Number(c[0]),String(c[1]),n+1):this.db.prepare(`SELECT * FROM phase2_campaign_members WHERE campaign_id=? ORDER BY ordinal,run_id LIMIT ?`).all(k,n+1)) as Row[];const more=rows.length>n,items=rows.slice(0,n).map(mrow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cursor([last.ordinal,last.runId]):null};}
  async upsertRecord(x:CreatePhase2RecordInput):Promise<{record:Phase2RecordRow;created:boolean}>{const k=id("p2r"),t=now();const z=this.db.prepare(`INSERT OR IGNORE INTO phase2_records(id,campaign_id,kind,signature,owner,status,source_operation_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(k,x.campaignId,x.kind,x.signature??null,x.owner??null,x.status??null,x.sourceOperationId,x.payloadJson,t);const r=this.db.prepare(`SELECT * FROM phase2_records WHERE campaign_id=? AND kind=? AND source_operation_id=?`).get(x.campaignId,x.kind,x.sourceOperationId) as Row;return{record:rrow(r),created:z.changes===1};}
  async listRecords(k:string,kind:Phase2RecordKind|null,req:Phase2PageRequest):Promise<Phase2Page<Phase2RecordRow>>{const n=limit(req.limit),c=decode(req.cursor);const where=kind?`campaign_id=? AND kind=?`:`campaign_id=?`,base=kind?[k,kind]:[k];let rows:Row[];if(c){rows=this.db.prepare(`SELECT * FROM phase2_records WHERE ${where} AND (created_at>? OR (created_at=? AND id>?)) ORDER BY created_at,id LIMIT ?`).all(...base,String(c[0]),String(c[0]),String(c[1]),n+1) as Row[]}else{rows=this.db.prepare(`SELECT * FROM phase2_records WHERE ${where} ORDER BY created_at,id LIMIT ?`).all(...base,n+1) as Row[]}const more=rows.length>n,items=rows.slice(0,n).map(rrow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cursor([last.createdAt,last.id]):null};}
  async createPublication(x:Omit<Phase2PublicationRow,"id"|"state"|"createdAt"|"publishedAt">):Promise<Phase2PublicationRow>{const k=id("p2p"),t=now();this.db.prepare(`INSERT INTO phase2_artifact_publications(id,campaign_id,run_id,phase1_archive_view_id,final_archive_view_id,manifest_sha256,state,created_at) VALUES(?,?,?,?,?,?,'preparing',?)`).run(k,x.campaignId,x.runId,x.phase1ArchiveViewId,x.finalArchiveViewId,x.manifestSha256,t);return prow(this.db.prepare(`SELECT * FROM phase2_artifact_publications WHERE id=?`).get(k) as Row);}
  async transitionPublication(k:string,s:Phase2PublicationRow["state"],n:Phase2PublicationRow["state"]):Promise<Phase2PublicationRow|null>{const p=n==="published"?now():null;const z=this.db.prepare(`UPDATE phase2_artifact_publications SET state=?,published_at=COALESCE(?,published_at) WHERE id=? AND state=?`).run(n,p,k,s);if(!z.changes)return null;return prow(this.db.prepare(`SELECT * FROM phase2_artifact_publications WHERE id=?`).get(k) as Row);}
  async listPublications(k:string,req:Phase2PageRequest):Promise<Phase2Page<Phase2PublicationRow>>{const n=limit(req.limit),c=decode(req.cursor);const rows=(c?this.db.prepare(`SELECT * FROM phase2_artifact_publications WHERE campaign_id=? AND (created_at>? OR (created_at=? AND id>?)) ORDER BY created_at,id LIMIT ?`).all(k,String(c[0]),String(c[0]),String(c[1]),n+1):this.db.prepare(`SELECT * FROM phase2_artifact_publications WHERE campaign_id=? ORDER BY created_at,id LIMIT ?`).all(k,n+1)) as Row[];const more=rows.length>n,items=rows.slice(0,n).map(prow),last=items.at(-1);return{items,hasMore:more,nextCursor:more&&last?cursor([last.createdAt,last.id]):null};}
}

/** Open the SQLite Phase-2 store. */
export function createSqlitePhase2Db(db: Database.Database): Phase2Db {
  migrate(db);
  const pipeline=new SqlitePipelineRepository(db),phase2=new SqlitePhase2Repository(db);
  return {pipeline,phase2,async transaction<T>(fn:(tx:Pick<Phase2Db,"pipeline"|"phase2">)=>Promise<T>):Promise<T>{db.exec("BEGIN IMMEDIATE");try{const out=await fn({pipeline,phase2});db.exec("COMMIT");return out}catch(e){db.exec("ROLLBACK");throw e}},async close(){db.close()}};
}
